# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: shell_scripts

jobs:
  build:
    name: Check for changes and make updates to publications.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
           architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install Python dependencies
          uses: py-actions/py-dependency-install@v2
          with:
            path: "build_tools/requirements.txt"
      - name: run shell script that calls python files
        run: ./shell_scripts/modification_and_duplicate_check.sh ${{ secrets.API_TOKEN_GITHUB }} ${{ secrets.ZOTERO_KEY }}

      - name: Push changes to sasview.github.io
        uses: sasview/saspubs@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'sasview-bot'
          destination-repository-name: 'saview.github.io'